use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

use crate::state::Theme;

// ── Claude Code hook detection / installation ──────────────────────────
//
// Hooks are installed as `"type": "command"` entries pointing at a shim
// script (`~/.coach/claude-hook.sh`). The shim forwards stdin to
// Coach's HTTP endpoint and prints the response. When Coach is offline
// the shim exits 0 with a `systemMessage` JSON for Stop/UserPromptSubmit
// hooks, and silently for PostToolUse/PermissionRequest — eliminating
// the "hook error" spam from the old `"type": "http"` approach.
// Install/uninstall automatically migrates away from legacy HTTP hooks.

fn claude_settings_path() -> PathBuf {
    dirs::home_dir()
        .expect("no home directory")
        .join(".claude")
        .join("settings.json")
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookEntryStatus {
    pub event: String,
    pub url: String,
    pub installed: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookStatus {
    pub installed: bool,
    pub path: String,
    pub hooks: Vec<HookEntryStatus>,
}

/// Shim script Coach drops into `~/.coach/` so Claude Code command hooks
/// can forward events via curl without erroring when Coach is offline.
pub fn claude_shim_path() -> PathBuf {
    dirs::home_dir()
        .expect("no home directory")
        .join(".coach")
        .join("claude-hook.sh")
}

const CLAUDE_SHIM_FILENAME: &str = "claude-hook.sh";

/// (Claude Code event name, URL slug under `/hook/`).
const CLAUDE_HOOK_EVENTS: &[(&str, &str)] = &[
    ("PermissionRequest", "permission-request"),
    ("Stop", "stop"),
    ("PostToolUse", "post-tool-use"),
    ("UserPromptSubmit", "user-prompt-submit"),
    // NOTE: SessionStart not included — Claude Code 2.1.92+ silently
    // drops hooks for it. `/clear` is detected lazily on the next tool
    // call via session_id-mismatch in `state::apply_hook_event`.
    // The HTTP route in server.rs stays wired up for Cursor's
    // `sessionStart` hook — see `CURSOR_HOOK_EVENTS`.
];

/// Body of the shim script for the given Coach port.
/// `--connect-timeout 2` avoids long hangs when Coach is down.
/// On failure, Stop and UserPromptSubmit return a JSON response with
/// `systemMessage` so Claude Code shows "Coach is offline" as a
/// warning. Other hooks exit 0 silently.
pub fn claude_shim_script(port: u16) -> String {
    format!(
        r#"#!/bin/sh
# Auto-generated by Coach — forwards hook events to the Coach server.
resp=$(curl -sS --connect-timeout 2 -X POST "http://127.0.0.1:{port}/hook/$1" \
     -H "Content-Type: application/json" \
     --data-binary @- 2>/dev/null)
if [ $? -eq 0 ]; then
    printf '%s' "$resp"
else
    case "$1" in
        stop|user-prompt-submit)
            printf '{{"systemMessage":"Coach is offline"}}' ;;
    esac
fi
"#,
    )
}

pub fn expected_hook_commands(shim_path: &std::path::Path) -> Vec<(&'static str, String)> {
    let shim = shim_path.display().to_string();
    CLAUDE_HOOK_EVENTS
        .iter()
        .map(|(event, slug)| (*event, format!("{shim} {slug}")))
        .collect()
}

/// True if this hook entry has a `"type": "command"` whose command string
/// matches `expected` exactly.
fn has_command_hook(entries: &[serde_json::Value], expected_cmd: &str) -> bool {
    entries
        .iter()
        .any(|entry| is_coach_command_entry(entry, expected_cmd))
}

/// Returns true if this hook entry contains a command hook matching the
/// given command string.
fn is_coach_command_entry(entry: &serde_json::Value, expected_cmd: &str) -> bool {
    entry
        .get("hooks")
        .and_then(|h| h.as_array())
        .is_some_and(|hooks| {
            hooks.iter().any(|hook| {
                hook.get("type").and_then(|t| t.as_str()) == Some("command")
                    && hook.get("command").and_then(|c| c.as_str()) == Some(expected_cmd)
            })
        })
}

/// Broader check: is this a Coach-managed hook entry? Matches both the
/// current shim-based command hooks and legacy HTTP hooks so both can be
/// cleaned up during install/uninstall.
fn is_managed_claude_entry(entry: &serde_json::Value) -> bool {
    entry
        .get("hooks")
        .and_then(|h| h.as_array())
        .is_some_and(|hooks| {
            hooks.iter().any(|hook| {
                // Current: command hook referencing our shim filename.
                let is_shim_cmd = hook.get("type").and_then(|t| t.as_str()) == Some("command")
                    && hook
                        .get("command")
                        .and_then(|c| c.as_str())
                        .is_some_and(|c| c.contains(CLAUDE_SHIM_FILENAME));
                // Legacy: HTTP hook pointing at localhost/hook/*.
                let is_legacy_http = hook.get("type").and_then(|t| t.as_str()) == Some("http")
                    && hook
                        .get("url")
                        .and_then(|u| u.as_str())
                        .is_some_and(|u| {
                            u.contains("/hook/")
                                && (u.contains("127.0.0.1:") || u.contains("localhost:"))
                        });
                is_shim_cmd || is_legacy_http
            })
        })
}

pub fn check_hook_status(port: u16) -> HookStatus {
    check_hook_status_at(port, &claude_settings_path(), &claude_shim_path())
}

pub fn check_hook_status_at(
    port: u16,
    path: &std::path::Path,
    shim_path: &std::path::Path,
) -> HookStatus {
    let _ = port; // port is baked into the shim; we match by command string
    let expected = expected_hook_commands(shim_path);

    let settings: serde_json::Value = std::fs::read_to_string(path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(serde_json::Value::Null);

    let hooks_obj = settings.get("hooks");

    let entries: Vec<HookEntryStatus> = expected
        .iter()
        .map(|(event, cmd)| {
            let installed = hooks_obj
                .and_then(|h| h.get(*event))
                .and_then(|arr| arr.as_array())
                .is_some_and(|entries| has_command_hook(entries, cmd));

            HookEntryStatus {
                event: event.to_string(),
                url: cmd.clone(),
                installed,
            }
        })
        .collect();

    let all_installed = entries.iter().all(|e| e.installed);

    HookStatus {
        installed: all_installed,
        path: path.display().to_string(),
        hooks: entries,
    }
}

/// Merge coach hooks into ~/.claude/settings.json, preserving existing hooks.
pub fn install_hooks(port: u16) -> Result<(), String> {
    install_hooks_at(port, &claude_settings_path(), &claude_shim_path())
}

/// Reconcile Coach-managed Claude Code hooks on startup.
///
/// Drives behaviour from the persistent intent flag (`hooks_user_enabled`),
/// not the on-disk presence of hooks. This matters because
/// `auto_uninstall_hooks_on_exit` deletes the on-disk entries on every clean
/// shutdown — without a separate intent flag we'd lose the "user opted in"
/// signal between sessions.
///
/// Behaviour:
///   * If `*user_enabled` is true: install any missing managed hooks.
///   * If `*user_enabled` is false but managed hooks already exist on disk
///     (legacy install or pre-flag user): flip the flag to true and install
///     any missing ones. This is a one-shot migration so existing users keep
///     working without re-clicking Install.
///   * Otherwise: no-op. First-time install stays explicit.
///
/// Returns the names of any newly-added hooks so the caller can log them.
pub fn sync_managed_hooks(port: u16, user_enabled: &mut bool) -> Result<Vec<String>, String> {
    sync_managed_hooks_at(port, &claude_settings_path(), &claude_shim_path(), user_enabled)
}

pub fn sync_managed_hooks_at(
    port: u16,
    path: &std::path::Path,
    shim_path: &std::path::Path,
    user_enabled: &mut bool,
) -> Result<Vec<String>, String> {
    let status = check_hook_status_at(port, path, shim_path);
    let any_installed = status.hooks.iter().any(|h| h.installed);

    // Legacy migration: hooks on disk but no recorded intent → adopt as
    // opted-in. Also detect old-style HTTP hooks as "opted in" so they
    // get migrated to command hooks.
    if !*user_enabled && (any_installed || has_any_legacy_http_hooks(path)) {
        *user_enabled = true;
    }

    if !*user_enabled {
        return Ok(vec![]);
    }

    let missing: Vec<String> = status
        .hooks
        .iter()
        .filter(|h| !h.installed)
        .map(|h| h.event.clone())
        .collect();
    if missing.is_empty() {
        return Ok(vec![]);
    }
    install_hooks_at(port, path, shim_path)?;
    Ok(missing)
}

/// Returns true if the settings file has any legacy HTTP hooks pointing
/// at Coach's `/hook/` endpoints. Used by sync to detect pre-shim
/// installs that need migration.
fn has_any_legacy_http_hooks(path: &std::path::Path) -> bool {
    let settings: serde_json::Value = std::fs::read_to_string(path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(serde_json::Value::Null);

    let Some(hooks_obj) = settings.get("hooks").and_then(|h| h.as_object()) else {
        return false;
    };
    hooks_obj.values().any(|event_arr| {
        event_arr
            .as_array()
            .is_some_and(|arr| arr.iter().any(|entry| {
                entry.get("hooks").and_then(|h| h.as_array()).is_some_and(|hooks| {
                    hooks.iter().any(|hook| {
                        hook.get("type").and_then(|t| t.as_str()) == Some("http")
                            && hook.get("url").and_then(|u| u.as_str()).is_some_and(|u| {
                                u.contains("/hook/")
                                    && (u.contains("127.0.0.1:") || u.contains("localhost:"))
                            })
                    })
                })
            }))
    })
}

pub fn install_hooks_at(
    port: u16,
    path: &std::path::Path,
    shim_path: &std::path::Path,
) -> Result<(), String> {
    // 1. Write the shim script so the command referenced by settings.json
    //    is on disk by the time the JSON is written.
    if let Some(parent) = shim_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::write(shim_path, claude_shim_script(port)).map_err(|e| e.to_string())?;
    crate::path_install::make_executable(shim_path)?;

    // 2. Merge our command hook entries into settings.json, preserving
    //    existing user entries. Legacy HTTP hooks are removed first.
    let expected = expected_hook_commands(shim_path);

    let mut settings: serde_json::Value = std::fs::read_to_string(path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(serde_json::json!({}));

    let settings_obj = settings
        .as_object_mut()
        .ok_or("Claude settings is not a JSON object")?;

    if !settings_obj.contains_key("hooks") {
        settings_obj.insert("hooks".into(), serde_json::json!({}));
    }

    let hooks_obj = settings_obj
        .get_mut("hooks")
        .and_then(|v| v.as_object_mut())
        .ok_or("hooks is not an object")?;

    // Sweep legacy Coach entries from *all* events (not just managed
    // ones) — e.g. SessionStart had an HTTP hook in older versions that
    // was later removed from the managed set.
    for event_arr in hooks_obj.values_mut() {
        if let Some(arr) = event_arr.as_array_mut() {
            arr.retain(|entry| !is_managed_claude_entry(entry));
        }
    }

    for (event, cmd) in &expected {
        let hook_entry = serde_json::json!({
            "hooks": [{"type": "command", "command": cmd}]
        });

        if let Some(existing) = hooks_obj.get_mut(*event) {
            if let Some(arr) = existing.as_array_mut() {
                if !has_command_hook(arr, cmd) {
                    arr.push(hook_entry);
                }
            }
        } else {
            hooks_obj.insert(event.to_string(), serde_json::json!([hook_entry]));
        }
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }

    let json = serde_json::to_string_pretty(&settings).map_err(|e| e.to_string())?;
    std::fs::write(path, json).map_err(|e| e.to_string())?;

    Ok(())
}

/// Remove coach hooks from ~/.claude/settings.json, preserving everything else.
pub fn uninstall_hooks(port: u16) -> Result<(), String> {
    uninstall_hooks_at(port, &claude_settings_path(), &claude_shim_path())
}

pub fn uninstall_hooks_at(
    port: u16,
    path: &std::path::Path,
    shim_path: &std::path::Path,
) -> Result<(), String> {
    let _ = port;
    let content = std::fs::read_to_string(path).map_err(|e| e.to_string())?;
    let mut settings: serde_json::Value =
        serde_json::from_str(&content).map_err(|e| e.to_string())?;

    let hooks_obj = settings
        .get_mut("hooks")
        .and_then(|v| v.as_object_mut())
        .ok_or("No hooks object in settings")?;

    // Remove both current command hooks and legacy HTTP hooks.
    for event_arr in hooks_obj.values_mut() {
        if let Some(arr) = event_arr.as_array_mut() {
            arr.retain(|entry| !is_managed_claude_entry(entry));
        }
    }

    // Clean up empty event arrays.
    let empty_events: Vec<String> = hooks_obj
        .iter()
        .filter(|(_, v)| v.as_array().is_some_and(|a| a.is_empty()))
        .map(|(k, _)| k.clone())
        .collect();
    for key in empty_events {
        hooks_obj.remove(&key);
    }

    let json = serde_json::to_string_pretty(&settings).map_err(|e| e.to_string())?;
    std::fs::write(path, json).map_err(|e| e.to_string())?;

    // Best-effort: remove the shim script.
    let _ = std::fs::remove_file(shim_path);

    Ok(())
}

// ── Cursor Agent hooks (`~/.cursor/hooks.json`, `command` + stdin JSON) ──
//
// Cursor's hook runner silently drops any hook command that mentions `curl`
// directly (verified against cursor-agent 2.4.28 — even prefixing with an
// unrelated `touch` doesn't slip past). We work around it by installing a
// shim script (`coach-cursor-hook.sh`, sibling of hooks.json) and pointing
// every hook entry at it: the shim is what calls curl. Hook command entries
// become `<shim path> <event-slug>`.

fn cursor_hooks_path() -> PathBuf {
    dirs::home_dir()
        .expect("no home directory")
        .join(".cursor")
        .join("hooks.json")
}

/// Shim script Coach drops next to hooks.json so hook entries can avoid
/// mentioning `curl` directly (Cursor's hook runner blocks that).
pub fn cursor_shim_path() -> PathBuf {
    dirs::home_dir()
        .expect("no home directory")
        .join(".cursor")
        .join("coach-cursor-hook.sh")
}

const CURSOR_SHIM_FILENAME: &str = "coach-cursor-hook.sh";

/// (cursor event name, URL slug under `/cursor/hook/`).
const CURSOR_HOOK_EVENTS: &[(&str, &str)] = &[
    ("sessionStart", "session-start"),
    ("beforeSubmitPrompt", "before-submit-prompt"),
    ("beforeShellExecution", "before-shell"),
    ("beforeMCPExecution", "before-mcp"),
    ("afterShellExecution", "after-shell"),
    ("afterMCPExecution", "after-mcp"),
    ("afterFileEdit", "after-file-edit"),
    ("stop", "stop"),
];

/// Body of the shim script for the given Coach port. `--data-binary @-`
/// forwards stdin verbatim. The trailing `|| true` ensures exit 0 so
/// Cursor doesn't show hook errors when Coach is offline.
pub fn cursor_shim_script(port: u16) -> String {
    format!(
        "#!/bin/sh\n\
         # Auto-generated by Coach — forwards hook events to the Coach server.\n\
         # Exits silently when Coach is offline.\n\
         curl -sS --connect-timeout 2 -X POST \"http://127.0.0.1:{port}/cursor/hook/$1\" \\\n\
              -H \"Content-Type: application/json\" \\\n\
              --data-binary @- 2>/dev/null || true\n",
    )
}

pub fn expected_cursor_hook_commands(shim_path: &std::path::Path) -> Vec<(&'static str, String)> {
    let shim = shim_path.display().to_string();
    CURSOR_HOOK_EVENTS
        .iter()
        .map(|(event, slug)| (*event, format!("{shim} {slug}")))
        .collect()
}

fn cursor_command_matches(entry: &serde_json::Value, expected: &str) -> bool {
    entry
        .get("command")
        .and_then(|c| c.as_str())
        .is_some_and(|cmd| cmd == expected)
}

/// A hook entry is "managed by Coach" if its command references our shim
/// script by filename, OR if it's a legacy `curl ... 127.0.0.1:.../cursor/hook/...`
/// entry from a pre-shim install. The legacy match requires both the route
/// path AND a localhost host so an unrelated user hook with `/cursor/hook/`
/// in some other context can't be swept up by reinstall.
fn is_managed_cursor_command(cmd: &str) -> bool {
    if cmd.contains(CURSOR_SHIM_FILENAME) {
        return true;
    }
    cmd.contains("/cursor/hook/")
        && (cmd.contains("127.0.0.1:") || cmd.contains("localhost:"))
}

pub fn check_cursor_hook_status() -> HookStatus {
    check_cursor_hook_status_at(&cursor_hooks_path(), &cursor_shim_path())
}

pub fn check_cursor_hook_status_at(
    hooks_path: &std::path::Path,
    shim_path: &std::path::Path,
) -> HookStatus {
    let expected = expected_cursor_hook_commands(shim_path);

    let settings: serde_json::Value = std::fs::read_to_string(hooks_path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(serde_json::Value::Null);

    let hooks_obj = settings.get("hooks");

    let entries: Vec<HookEntryStatus> = expected
        .iter()
        .map(|(event, cmd)| {
            let installed = hooks_obj
                .and_then(|h| h.get(*event))
                .and_then(|arr| arr.as_array())
                .is_some_and(|entries| entries.iter().any(|e| cursor_command_matches(e, cmd)));

            HookEntryStatus {
                event: event.to_string(),
                url: cmd.clone(),
                installed,
            }
        })
        .collect();

    let all_installed = entries.iter().all(|e| e.installed);

    HookStatus {
        installed: all_installed,
        path: hooks_path.display().to_string(),
        hooks: entries,
    }
}

pub fn install_cursor_hooks(port: u16) -> Result<(), String> {
    install_cursor_hooks_at(port, &cursor_hooks_path(), &cursor_shim_path())
}

pub fn install_cursor_hooks_at(
    port: u16,
    hooks_path: &std::path::Path,
    shim_path: &std::path::Path,
) -> Result<(), String> {
    // 1. Write the shim script first so the executable referenced by
    //    hooks.json is on disk by the time the JSON is written.
    if let Some(parent) = shim_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::write(shim_path, cursor_shim_script(port)).map_err(|e| e.to_string())?;
    crate::path_install::make_executable(shim_path)?;

    // 2. Merge our hook entries into hooks.json, preserving any existing
    //    user entries (e.g. gleaner-cursor-upload).
    let expected = expected_cursor_hook_commands(shim_path);

    let mut settings: serde_json::Value = std::fs::read_to_string(hooks_path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_else(|| serde_json::json!({ "version": 1, "hooks": {} }));

    let settings_obj = settings
        .as_object_mut()
        .ok_or("Cursor hooks.json must be a JSON object")?;

    if !settings_obj.contains_key("version") {
        settings_obj.insert("version".into(), serde_json::json!(1));
    }
    if !settings_obj.contains_key("hooks") {
        settings_obj.insert("hooks".into(), serde_json::json!({}));
    }

    let hooks_obj = settings_obj
        .get_mut("hooks")
        .and_then(|v| v.as_object_mut())
        .ok_or("hooks must be an object")?;

    for (event, cmd) in &expected {
        // Drop any stale Coach-managed entry first (different shim path
        // from a previous install) so we don't accumulate dead commands.
        if let Some(existing) = hooks_obj.get_mut(*event) {
            if let Some(arr) = existing.as_array_mut() {
                arr.retain(|entry| {
                    entry
                        .get("command")
                        .and_then(|c| c.as_str())
                        .map(|c| !is_managed_cursor_command(c))
                        .unwrap_or(true)
                });
            }
        }
        let entry = serde_json::json!({ "command": cmd });
        if let Some(existing) = hooks_obj.get_mut(*event) {
            if let Some(arr) = existing.as_array_mut() {
                if !arr.iter().any(|e| cursor_command_matches(e, cmd)) {
                    arr.push(entry);
                }
            }
        } else {
            hooks_obj.insert((*event).to_string(), serde_json::json!([entry]));
        }
    }

    if let Some(parent) = hooks_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }

    let json = serde_json::to_string_pretty(&settings).map_err(|e| e.to_string())?;
    std::fs::write(hooks_path, json).map_err(|e| e.to_string())?;

    Ok(())
}

pub fn uninstall_cursor_hooks() -> Result<(), String> {
    uninstall_cursor_hooks_at(&cursor_hooks_path(), &cursor_shim_path())
}

pub fn uninstall_cursor_hooks_at(
    hooks_path: &std::path::Path,
    shim_path: &std::path::Path,
) -> Result<(), String> {
    let content = std::fs::read_to_string(hooks_path).map_err(|e| e.to_string())?;
    let mut settings: serde_json::Value =
        serde_json::from_str(&content).map_err(|e| e.to_string())?;

    let hooks_obj = settings
        .get_mut("hooks")
        .and_then(|v| v.as_object_mut())
        .ok_or("No hooks object in Cursor hooks.json")?;

    for (_event, arr_val) in hooks_obj.iter_mut() {
        if let Some(arr) = arr_val.as_array_mut() {
            arr.retain(|entry| {
                entry
                    .get("command")
                    .and_then(|c| c.as_str())
                    .map(|cmd| !is_managed_cursor_command(cmd))
                    .unwrap_or(true)
            });
        }
    }

    let empty_events: Vec<String> = hooks_obj
        .iter()
        .filter(|(_, v)| v.as_array().is_some_and(|a| a.is_empty()))
        .map(|(k, _)| k.clone())
        .collect();
    for key in empty_events {
        hooks_obj.remove(&key);
    }

    let json = serde_json::to_string_pretty(&settings).map_err(|e| e.to_string())?;
    std::fs::write(hooks_path, json).map_err(|e| e.to_string())?;

    // Best-effort: remove the shim script. If it's already gone (or
    // shared with something else), don't error.
    let _ = std::fs::remove_file(shim_path);

    Ok(())
}

/// Cursor twin of `sync_managed_hooks`. See that function for the rationale
/// behind the `user_enabled` flag and the legacy migration.
pub fn sync_managed_cursor_hooks(
    port: u16,
    user_enabled: &mut bool,
) -> Result<Vec<String>, String> {
    sync_managed_cursor_hooks_at(port, &cursor_hooks_path(), &cursor_shim_path(), user_enabled)
}

pub fn sync_managed_cursor_hooks_at(
    port: u16,
    hooks_path: &std::path::Path,
    shim_path: &std::path::Path,
    user_enabled: &mut bool,
) -> Result<Vec<String>, String> {
    let status = check_cursor_hook_status_at(hooks_path, shim_path);
    let any_installed = status.hooks.iter().any(|h| h.installed);

    if !*user_enabled && any_installed {
        *user_enabled = true;
    }
    if !*user_enabled {
        return Ok(vec![]);
    }

    let missing: Vec<String> = status
        .hooks
        .iter()
        .filter(|h| !h.installed)
        .map(|h| h.event.clone())
        .collect();
    if missing.is_empty() {
        return Ok(vec![]);
    }
    install_cursor_hooks_at(port, hooks_path, shim_path)?;
    Ok(missing)
}

// ── Exit-time cleanup ────────────────────────────────────────────────────

/// Best-effort hook cleanup on Coach shutdown. Reads `~/.coach/settings.json`
/// from disk so the call site can be a sync shutdown callback that has no
/// access to (or shouldn't be locking) the in-memory `CoachState`.
///
/// No-op if `auto_uninstall_hooks_on_exit` is false. Removes Claude and/or
/// Cursor managed hooks based on the persistent intent flags. Errors are
/// logged but never panic — shutdown must always make progress.
pub fn cleanup_hooks_on_exit() {
    cleanup_hooks_on_exit_at(
        &Settings::load(),
        &claude_settings_path(),
        &claude_shim_path(),
        &cursor_hooks_path(),
        &cursor_shim_path(),
    );
}

/// Path-injectable variant for unit tests.
pub fn cleanup_hooks_on_exit_at(
    settings: &Settings,
    claude_path: &std::path::Path,
    claude_shim: &std::path::Path,
    cursor_path: &std::path::Path,
    cursor_shim: &std::path::Path,
) {
    if !settings.auto_uninstall_hooks_on_exit {
        return;
    }
    if settings.hooks_user_enabled && claude_path.exists() {
        match uninstall_hooks_at(settings.port, claude_path, claude_shim) {
            Ok(()) => eprintln!("[coach] cleanup: removed Claude Code hooks"),
            Err(e) => eprintln!("[coach] cleanup: Claude hook removal failed: {e}"),
        }
    }
    if settings.cursor_hooks_user_enabled && cursor_path.exists() {
        match uninstall_cursor_hooks_at(cursor_path, cursor_shim) {
            Ok(()) => eprintln!("[coach] cleanup: removed Cursor hooks"),
            Err(e) => eprintln!("[coach] cleanup: Cursor hook removal failed: {e}"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelConfig {
    pub provider: String,
    pub model: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum EngineMode {
    /// Rule-based: pattern-matching only, no LLM calls.
    Rules,
    /// LLM-powered: sends context to the configured model for evaluation.
    Llm,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CoachRule {
    pub id: String,
    pub enabled: bool,
}

/// Env var name for each provider.
/// Env var names per provider. Multiple names are checked in order (first match wins).
pub const PROVIDER_ENV_VARS: &[(&str, &[&str])] = &[
    ("google", &["GEMINI_API_KEY", "GOOGLE_API_KEY"]),
    ("anthropic", &["ANTHROPIC_API_KEY"]),
    ("openai", &["OPENAI_API_KEY"]),
    ("openrouter", &["OPENROUTER_API_KEY"]),
];

/// Read all available API tokens from environment variables.
pub fn env_tokens() -> HashMap<String, String> {
    PROVIDER_ENV_VARS
        .iter()
        .filter_map(|(provider, vars)| {
            vars.iter()
                .find_map(|var| std::env::var(var).ok().filter(|v| !v.is_empty()))
                .map(|v| (provider.to_string(), v))
        })
        .collect()
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Settings {
    #[serde(default)]
    pub api_tokens: HashMap<String, String>,
    #[serde(default = "default_model")]
    pub model: ModelConfig,
    #[serde(default = "default_priorities")]
    pub priorities: Vec<String>,
    #[serde(default = "default_theme")]
    pub theme: Theme,
    #[serde(default = "default_port")]
    pub port: u16,
    #[serde(default = "default_coach_mode")]
    pub coach_mode: EngineMode,
    #[serde(default = "default_rules")]
    pub rules: Vec<CoachRule>,
    /// On clean exit, uninstall Coach's hooks from `~/.claude/settings.json`
    /// and `~/.cursor/hooks.json` so that other live Claude/Cursor sessions
    /// don't fail with "HTTP undefined" when they try to call the now-stopped
    /// hook server. Default true; users can opt out if they'd rather see
    /// the failures as a signal that Coach isn't running. Re-installation
    /// happens automatically on next startup based on `hooks_user_enabled` /
    /// `cursor_hooks_user_enabled`.
    #[serde(default = "default_true")]
    pub auto_uninstall_hooks_on_exit: bool,
    /// Persistent record of the user's intent to use Claude Code hooks. Set
    /// when the user clicks Install, cleared when they click Uninstall. Survives
    /// auto-cleanup-on-exit so the next startup knows to reinstall. Migrated
    /// to `true` on first run if hooks are already on disk.
    #[serde(default)]
    pub hooks_user_enabled: bool,
    /// Same idea, for Cursor Agent hooks.
    #[serde(default)]
    pub cursor_hooks_user_enabled: bool,
}

fn default_model() -> ModelConfig {
    ModelConfig {
        provider: "openai".into(),
        model: "gpt-5.4-mini".into(),
    }
}

/// Providers that support stateful coach sessions via `session_send`.
/// Three mechanisms, in decreasing cost efficiency:
///   • OpenAI: server-side state via Responses API + previous_response_id
///     (native, O(1) per call).
///   • Anthropic: client-side message history with prompt caching
///     (emulated, ~10% of full input cost on the cached prefix).
///   • Google Gemini: client-side message history, no usable prefix
///     cache — full input charged every call (emulated, O(N) per call).
///     Pair with a cheap Flash model to keep observer cost tolerable.
/// Other providers (openrouter, …) can still serve the rules engine
/// and one-shot stop evaluation; they just can't accumulate observer
/// context at all.
pub const OBSERVER_CAPABLE_PROVIDERS: &[&str] = &["openai", "anthropic", "google"];

fn default_priorities() -> Vec<String> {
    vec![
        "Code simplicity".into(),
        "Performance".into(),
        "Feature completeness".into(),
    ]
}

fn default_theme() -> Theme {
    Theme::System
}

fn default_port() -> u16 {
    7700
}

fn default_coach_mode() -> EngineMode {
    EngineMode::Rules
}

fn default_rules() -> Vec<CoachRule> {
    vec![CoachRule {
        id: "outdated_models".into(),
        enabled: true,
    }]
}

fn default_true() -> bool {
    true
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            api_tokens: HashMap::new(),
            model: default_model(),
            priorities: default_priorities(),
            theme: default_theme(),
            port: default_port(),
            coach_mode: default_coach_mode(),
            rules: default_rules(),
            auto_uninstall_hooks_on_exit: default_true(),
            hooks_user_enabled: false,
            cursor_hooks_user_enabled: false,
        }
    }
}

/// Default location of `~/.coach/settings.json`. Exposed so the CLI
/// can show users where it's reading from / writing to.
pub fn settings_path() -> PathBuf {
    dirs::home_dir()
        .expect("no home directory")
        .join(".coach")
        .join("settings.json")
}

impl Settings {
    pub fn load() -> Self {
        Self::load_from(&settings_path())
    }

    /// Path-injectable load. Used by `Settings::load` in production and
    /// directly by the CLI's `--config-file` override and unit tests.
    pub fn load_from(path: &std::path::Path) -> Self {
        match std::fs::read_to_string(path) {
            Ok(contents) => serde_json::from_str(&contents).unwrap_or_else(|e| {
                eprintln!("Warning: failed to parse {}: {}", path.display(), e);
                Self::default()
            }),
            Err(_) => Self::default(),
        }
    }

    pub fn save(&self) {
        self.save_to(&settings_path());
    }

    /// Path-injectable save. Errors here are eprintln!'d rather than
    /// returned so the GUI's hot path stays infallible — the CLI uses
    /// the same code path and gets the same warning on stderr.
    pub fn save_to(&self, path: &std::path::Path) {
        if let Some(parent) = path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        match serde_json::to_string_pretty(self) {
            Ok(json) => {
                if let Err(e) = std::fs::write(path, json) {
                    eprintln!("Warning: failed to write {}: {}", path.display(), e);
                }
            }
            Err(e) => eprintln!("Warning: failed to serialize settings: {}", e),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Default values ──────────────────────────────────────────────────

    /// Default model should be OpenAI gpt-5.4-mini — observer requires
    /// OpenAI's Responses API for stateful coach sessions.
    #[test]
    fn default_model_is_openai_mini() {
        let s = Settings::default();
        assert_eq!(s.model.provider, "openai");
        assert_eq!(s.model.model, "gpt-5.4-mini");
    }

    /// OpenAI must be in the observer-capable list (it's the one provider
    /// rig 0.34 lets us chain via previous_response_id).
    #[test]
    fn openai_is_observer_capable() {
        assert!(OBSERVER_CAPABLE_PROVIDERS.contains(&"openai"));
    }

    /// Anthropic is observer-capable via client-side history + prompt
    /// caching. rig 0.34 exposes `with_automatic_caching()` first-class.
    #[test]
    fn anthropic_is_observer_capable() {
        assert!(OBSERVER_CAPABLE_PROVIDERS.contains(&"anthropic"));
    }

    /// Google is observer-capable via the emulated path: client-side
    /// history, no prefix caching. Cost scales with conversation length,
    /// so users should pair it with a cheap Flash model.
    #[test]
    fn google_is_observer_capable() {
        assert!(OBSERVER_CAPABLE_PROVIDERS.contains(&"google"));
    }

    /// openrouter remains unsupported: it's a chat-completions proxy
    /// with no session primitive and no caching primitive we can drive.
    #[test]
    fn openrouter_is_not_observer_capable() {
        assert!(!OBSERVER_CAPABLE_PROVIDERS.contains(&"openrouter"));
    }

    /// Priorities should ship with sensible non-empty defaults so the
    /// coach has something to say on first launch.
    #[test]
    fn default_priorities_are_non_empty() {
        let s = Settings::default();
        assert!(!s.priorities.is_empty());
    }

    /// Default port should be 7700, matching the hardcoded hook URLs
    /// and frontend expectations.
    #[test]
    fn default_port_is_7700() {
        let s = Settings::default();
        assert_eq!(s.port, 7700);
    }

    /// Default theme should be System so the app matches OS appearance.
    #[test]
    fn default_theme_is_system() {
        let s = Settings::default();
        assert_eq!(s.theme, Theme::System);
    }

    // ── Serde roundtrip ─────────────────────────────────────────────────

    /// Serializing Settings to JSON and deserializing back should
    /// preserve all fields exactly. This guards against accidentally
    /// breaking persistence when adding new fields.
    #[test]
    fn settings_serde_roundtrip_preserves_all_fields() {
        let original = Settings {
            api_tokens: HashMap::from([
                ("google".into(), "gk-123".into()),
                ("openai".into(), "sk-abc".into()),
            ]),
            model: ModelConfig {
                provider: "anthropic".into(),
                model: "claude-sonnet-4-20250514".into(),
            },
            priorities: vec!["Speed".into(), "Safety".into()],
            theme: Theme::Dark,
            port: 9999,
            coach_mode: EngineMode::Llm,
            rules: vec![
                CoachRule { id: "outdated_models".into(), enabled: false },
            ],
            auto_uninstall_hooks_on_exit: false,
            hooks_user_enabled: true,
            cursor_hooks_user_enabled: true,
        };

        let json = serde_json::to_string(&original).unwrap();
        let restored: Settings = serde_json::from_str(&json).unwrap();

        assert_eq!(restored.api_tokens, original.api_tokens);
        assert_eq!(restored.model.provider, original.model.provider);
        assert_eq!(restored.model.model, original.model.model);
        assert_eq!(restored.priorities, original.priorities);
        assert_eq!(restored.theme, original.theme);
        assert_eq!(restored.port, original.port);
        assert_eq!(restored.coach_mode, original.coach_mode);
        assert_eq!(restored.rules, original.rules);
        assert_eq!(
            restored.auto_uninstall_hooks_on_exit,
            original.auto_uninstall_hooks_on_exit
        );
        assert_eq!(restored.hooks_user_enabled, original.hooks_user_enabled);
        assert_eq!(
            restored.cursor_hooks_user_enabled,
            original.cursor_hooks_user_enabled
        );
    }

    /// Deserializing an empty JSON object `{}` should produce the same
    /// defaults as `Settings::default()`. This ensures serde(default)
    /// attributes are correctly set on every field.
    #[test]
    fn empty_json_deserializes_to_defaults() {
        let from_json: Settings = serde_json::from_str("{}").unwrap();
        let defaults = Settings::default();

        assert_eq!(from_json.model.provider, defaults.model.provider);
        assert_eq!(from_json.model.model, defaults.model.model);
        assert_eq!(from_json.priorities, defaults.priorities);
        assert_eq!(from_json.theme, defaults.theme);
        assert_eq!(from_json.port, defaults.port);
        assert!(from_json.api_tokens.is_empty());
        // New hook-cleanup fields default sensibly: opt-in to cleanup,
        // opt-out of any auto-install. Users upgrading from older Coach
        // versions get these defaults silently.
        assert!(from_json.auto_uninstall_hooks_on_exit);
        assert!(!from_json.hooks_user_enabled);
        assert!(!from_json.cursor_hooks_user_enabled);
    }

    // ── has_command_hook helper ─────────────────────────────────────────

    #[test]
    fn has_command_hook_finds_matching_entry() {
        let entries: Vec<serde_json::Value> = vec![serde_json::json!({
            "hooks": [{"type": "command", "command": "/shim stop"}]
        })];
        assert!(has_command_hook(&entries, "/shim stop"));
    }

    #[test]
    fn has_command_hook_rejects_non_matching_command() {
        let entries: Vec<serde_json::Value> = vec![serde_json::json!({
            "hooks": [{"type": "command", "command": "/shim stop"}]
        })];
        assert!(!has_command_hook(&entries, "/other-shim stop"));
    }

    #[test]
    fn has_command_hook_returns_false_for_empty_array() {
        let entries: Vec<serde_json::Value> = vec![];
        assert!(!has_command_hook(&entries, "/shim stop"));
    }

    #[test]
    fn has_command_hook_ignores_non_command_types() {
        let entries: Vec<serde_json::Value> = vec![serde_json::json!({
            "hooks": [{"type": "http", "url": "http://localhost:7700/hook/stop"}]
        })];
        assert!(!has_command_hook(&entries, "http://localhost:7700/hook/stop"));
    }

    // ── is_managed_claude_entry ─────────────────────────────────────────

    #[test]
    fn is_managed_detects_shim_command() {
        let entry = serde_json::json!({
            "hooks": [{"type": "command", "command": "/home/u/.coach/claude-hook.sh stop"}]
        });
        assert!(is_managed_claude_entry(&entry));
    }

    #[test]
    fn is_managed_detects_legacy_http() {
        let entry = serde_json::json!({
            "hooks": [{"type": "http", "url": "http://localhost:7700/hook/stop"}]
        });
        assert!(is_managed_claude_entry(&entry));
    }

    #[test]
    fn is_managed_ignores_user_hooks() {
        let entry = serde_json::json!({
            "hooks": [{"type": "command", "command": "echo stopped"}]
        });
        assert!(!is_managed_claude_entry(&entry));
    }

    // ── Helper: temp shim path for tests ────────────────────────────────

    fn test_shim(dir: &std::path::Path) -> PathBuf {
        dir.join(CLAUDE_SHIM_FILENAME)
    }

    // ── check_hook_status with path ─────────────────────────────────────

    #[test]
    fn check_hook_status_reports_not_installed_for_missing_file() {
        let dir = tempfile::tempdir().unwrap();
        let shim = test_shim(dir.path());
        let status = check_hook_status_at(7700, std::path::Path::new("/nonexistent/path.json"), &shim);
        assert!(!status.installed);
        assert!(status.hooks.iter().all(|h| !h.installed));
        assert_eq!(status.hooks.len(), 4);
    }

    #[test]
    fn install_then_check_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        install_hooks_at(7700, &path, &shim).unwrap();
        let status = check_hook_status_at(7700, &path, &shim);

        assert!(status.installed);
        assert!(status.hooks.iter().all(|h| h.installed));
        assert!(shim.exists());
        let script = std::fs::read_to_string(&shim).unwrap();
        assert!(script.contains("Coach is offline"), "shim must handle offline case");
        assert!(script.contains("7700"), "shim must reference the configured port");
    }

    #[test]
    fn install_hooks_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        install_hooks_at(7700, &path, &shim).unwrap();
        install_hooks_at(7700, &path, &shim).unwrap();

        let content: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        for event in ["PermissionRequest", "Stop", "PostToolUse", "UserPromptSubmit"] {
            let arr = content["hooks"][event].as_array().unwrap();
            assert_eq!(arr.len(), 1, "event {event} should have exactly 1 entry after double install");
        }
    }

    #[test]
    fn install_hooks_preserves_existing_settings() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        let existing = serde_json::json!({
            "permissions": {"allow": ["Bash"]},
            "hooks": {
                "Stop": [{"hooks": [{"type": "command", "command": "echo stopped"}]}]
            }
        });
        std::fs::write(&path, serde_json::to_string_pretty(&existing).unwrap()).unwrap();

        install_hooks_at(7700, &path, &shim).unwrap();

        let content: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        assert_eq!(content["permissions"]["allow"][0], "Bash");
        let stop_entries = content["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop_entries.len(), 2, "existing user command hook + new coach command hook");
    }

    /// Install must replace legacy HTTP hooks with command hooks.
    #[test]
    fn install_migrates_legacy_http_hooks() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        let legacy = serde_json::json!({
            "hooks": {
                "Stop": [{"hooks": [{"type": "http", "url": "http://localhost:7700/hook/stop"}]}],
                "PostToolUse": [{"hooks": [{"type": "http", "url": "http://localhost:7700/hook/post-tool-use"}]}]
            }
        });
        std::fs::write(&path, serde_json::to_string_pretty(&legacy).unwrap()).unwrap();

        install_hooks_at(7700, &path, &shim).unwrap();

        let content: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        for event in ["Stop", "PostToolUse", "PermissionRequest", "UserPromptSubmit"] {
            let arr = content["hooks"][event].as_array().unwrap();
            assert_eq!(arr.len(), 1, "{event}: should have exactly 1 entry");
            assert_eq!(arr[0]["hooks"][0]["type"], "command", "{event}: must be command, not http");
        }
    }

    // ── uninstall_hooks ────────────────────────────────────────────────

    #[test]
    fn uninstall_reverses_install() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        install_hooks_at(7700, &path, &shim).unwrap();
        uninstall_hooks_at(7700, &path, &shim).unwrap();

        let status = check_hook_status_at(7700, &path, &shim);
        assert!(!status.installed);
        assert!(status.hooks.iter().all(|h| !h.installed));
        assert!(!shim.exists());
    }

    /// Uninstall should also clean up legacy HTTP hooks.
    #[test]
    fn uninstall_removes_legacy_http_hooks() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        let legacy = serde_json::json!({
            "hooks": {
                "Stop": [{"hooks": [{"type": "http", "url": "http://localhost:7700/hook/stop"}]}]
            }
        });
        std::fs::write(&path, serde_json::to_string_pretty(&legacy).unwrap()).unwrap();

        uninstall_hooks_at(7700, &path, &shim).unwrap();

        let content: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let hooks = content["hooks"].as_object().unwrap();
        assert!(hooks.is_empty());
    }

    #[test]
    fn uninstall_preserves_other_hooks() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        let existing = serde_json::json!({
            "permissions": {"allow": ["Bash"]},
            "hooks": {
                "Stop": [{"hooks": [{"type": "command", "command": "echo stopped"}]}]
            }
        });
        std::fs::write(&path, serde_json::to_string_pretty(&existing).unwrap()).unwrap();

        install_hooks_at(7700, &path, &shim).unwrap();
        uninstall_hooks_at(7700, &path, &shim).unwrap();

        let content: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        assert_eq!(content["permissions"]["allow"][0], "Bash");
        let stop_entries = content["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop_entries.len(), 1);
        assert_eq!(stop_entries[0]["hooks"][0]["command"], "echo stopped");
    }

    #[test]
    fn uninstall_removes_empty_event_arrays() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        install_hooks_at(7700, &path, &shim).unwrap();
        uninstall_hooks_at(7700, &path, &shim).unwrap();

        let content: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let hooks = content["hooks"].as_object().unwrap();
        assert!(hooks.is_empty());
    }

    // ── sync_managed_hooks ──────────────────────────────────────────────

    #[test]
    fn sync_does_nothing_when_unenabled_and_no_hooks() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());
        std::fs::write(&path, "{}").unwrap();

        let mut user_enabled = false;
        let added = sync_managed_hooks_at(7700, &path, &shim, &mut user_enabled).unwrap();
        assert!(added.is_empty());
        assert!(!user_enabled);

        let status = check_hook_status_at(7700, &path, &shim);
        assert!(!status.installed);
    }

    /// Legacy HTTP hooks on disk → sync adopts them, migrates to command.
    #[test]
    fn sync_migrates_legacy_install_and_fills_missing() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        let partial = serde_json::json!({
            "hooks": {
                "PostToolUse": [{
                    "hooks": [{"type": "http", "url": "http://localhost:7700/hook/post-tool-use"}]
                }]
            }
        });
        std::fs::write(&path, serde_json::to_string_pretty(&partial).unwrap()).unwrap();

        let mut user_enabled = false;
        let added = sync_managed_hooks_at(7700, &path, &shim, &mut user_enabled).unwrap();

        assert!(user_enabled, "legacy install flips intent flag on");
        // All four events should be added (legacy HTTP doesn't count as current command hook).
        assert_eq!(added.len(), 4);

        let status = check_hook_status_at(7700, &path, &shim);
        assert!(status.installed);

        // Legacy HTTP hook should be replaced.
        let content: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let pt = content["hooks"]["PostToolUse"].as_array().unwrap();
        assert_eq!(pt.len(), 1);
        assert_eq!(pt[0]["hooks"][0]["type"], "command");
    }

    #[test]
    fn sync_reinstalls_after_cleanup_when_intent_true() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        let mut user_enabled = true;
        let added = sync_managed_hooks_at(7700, &path, &shim, &mut user_enabled).unwrap();
        assert!(!added.is_empty());

        let status = check_hook_status_at(7700, &path, &shim);
        assert!(status.installed);
    }

    #[test]
    fn sync_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        let mut user_enabled = true;
        sync_managed_hooks_at(7700, &path, &shim, &mut user_enabled).unwrap();
        let added = sync_managed_hooks_at(7700, &path, &shim, &mut user_enabled).unwrap();
        assert!(added.is_empty(), "fully-installed state requires no sync");
    }

    #[test]
    fn sync_preserves_non_coach_hooks() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("settings.json");
        let shim = test_shim(dir.path());

        let shim_str = shim.display().to_string();
        let mixed = serde_json::json!({
            "hooks": {
                "Stop": [
                    {"hooks": [{"type": "command", "command": "echo user-hook"}]},
                    {"hooks": [{"type": "command", "command": format!("{shim_str} stop")}]}
                ]
            }
        });
        std::fs::write(&path, serde_json::to_string_pretty(&mixed).unwrap()).unwrap();

        let mut user_enabled = false;
        sync_managed_hooks_at(7700, &path, &shim, &mut user_enabled).unwrap();

        let content: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let stop_entries = content["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop_entries.len(), 2);
        let user_hooks: Vec<_> = stop_entries
            .iter()
            .filter(|e| e["hooks"][0]["command"].as_str().is_some_and(|c| c == "echo user-hook"))
            .collect();
        assert_eq!(user_hooks.len(), 1, "user hook must survive sync");
    }

    // ── cleanup_hooks_on_exit_at ────────────────────────────────────────

    /// The whole-cycle property test: install hooks, run the cleanup
    /// (mimicking app shutdown), then sync (mimicking next startup) — the
    /// final on-disk state should match the original install.
    #[test]
    fn install_cleanup_sync_roundtrip_matches_original() {
        let dir = tempfile::tempdir().unwrap();
        let claude = dir.path().join("claude_settings.json");
        let claude_shim = dir.path().join(CLAUDE_SHIM_FILENAME);
        let cursor_hooks = dir.path().join("cursor_hooks.json");
        let cursor_shim = dir.path().join("coach-cursor-hook.sh");

        // User opts in to both surfaces.
        install_hooks_at(7700, &claude, &claude_shim).unwrap();
        install_cursor_hooks_at(7700, &cursor_hooks, &cursor_shim).unwrap();
        let original_claude = std::fs::read_to_string(&claude).unwrap();
        let original_cursor = std::fs::read_to_string(&cursor_hooks).unwrap();

        // Simulate app shutdown with auto-uninstall enabled.
        let settings = Settings {
            auto_uninstall_hooks_on_exit: true,
            hooks_user_enabled: true,
            cursor_hooks_user_enabled: true,
            port: 7700,
            ..Settings::default()
        };
        cleanup_hooks_on_exit_at(&settings, &claude, &claude_shim, &cursor_hooks, &cursor_shim);

        // After cleanup, neither file should still contain managed hooks.
        assert!(!check_hook_status_at(7700, &claude, &claude_shim).installed);
        assert!(!check_cursor_hook_status_at(&cursor_hooks, &cursor_shim).installed);

        // Simulate next startup: sync re-installs based on intent flags.
        let mut hooks_intent = true;
        let mut cursor_intent = true;
        sync_managed_hooks_at(7700, &claude, &claude_shim, &mut hooks_intent).unwrap();
        sync_managed_cursor_hooks_at(7700, &cursor_hooks, &cursor_shim, &mut cursor_intent)
            .unwrap();

        // The end state should be byte-equivalent to the original install.
        assert_eq!(std::fs::read_to_string(&claude).unwrap(), original_claude);
        assert_eq!(std::fs::read_to_string(&cursor_hooks).unwrap(), original_cursor);
    }

    /// When auto-uninstall is disabled, cleanup is a no-op even with
    /// intent flags set.
    #[test]
    fn cleanup_is_noop_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let claude = dir.path().join("claude_settings.json");
        let claude_shim = dir.path().join(CLAUDE_SHIM_FILENAME);
        let cursor_hooks = dir.path().join("cursor_hooks.json");
        let cursor_shim = dir.path().join("coach-cursor-hook.sh");

        install_hooks_at(7700, &claude, &claude_shim).unwrap();
        install_cursor_hooks_at(7700, &cursor_hooks, &cursor_shim).unwrap();

        let settings = Settings {
            auto_uninstall_hooks_on_exit: false,
            hooks_user_enabled: true,
            cursor_hooks_user_enabled: true,
            port: 7700,
            ..Settings::default()
        };
        cleanup_hooks_on_exit_at(&settings, &claude, &claude_shim, &cursor_hooks, &cursor_shim);

        assert!(check_hook_status_at(7700, &claude, &claude_shim).installed);
        assert!(check_cursor_hook_status_at(&cursor_hooks, &cursor_shim).installed);
    }

    /// Cleanup ignores surfaces the user never opted in to.
    #[test]
    fn cleanup_only_touches_enabled_surfaces() {
        let dir = tempfile::tempdir().unwrap();
        let claude = dir.path().join("claude_settings.json");
        let claude_shim = dir.path().join(CLAUDE_SHIM_FILENAME);
        let cursor_hooks = dir.path().join("cursor_hooks.json");
        let cursor_shim = dir.path().join("coach-cursor-hook.sh");

        install_hooks_at(7700, &claude, &claude_shim).unwrap();
        install_cursor_hooks_at(7700, &cursor_hooks, &cursor_shim).unwrap();
        let cursor_before = std::fs::read_to_string(&cursor_hooks).unwrap();

        let settings = Settings {
            auto_uninstall_hooks_on_exit: true,
            hooks_user_enabled: true,
            cursor_hooks_user_enabled: false,
            port: 7700,
            ..Settings::default()
        };
        cleanup_hooks_on_exit_at(&settings, &claude, &claude_shim, &cursor_hooks, &cursor_shim);

        assert!(!check_hook_status_at(7700, &claude, &claude_shim).installed);
        assert_eq!(std::fs::read_to_string(&cursor_hooks).unwrap(), cursor_before);
    }
}
